SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.DATETIME > b.DATETIME
ORDER BY a.DATETIME ASC;

# SELECT a.ANIMAL_ID, a.NAME
# FROM ANIMAL_INS a, ANIMAL_OUTS b
# WHERE a.ANIMAL_ID = b.ANIMAL_ID AND a.DATETIME > b.DATETIME
# GROUP BY a.ANIMAL_ID
# ORDER BY a.DATETIME ASC; 
