SELECT 
    CRCC.CAR_ID, 
    CRCC.CAR_TYPE, 
    ROUND(CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCRH.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01'AND START_DATE <= '2022-12-01'
) AND CRCDP.DURATION_TYPE LIKE '30%'
GROUP BY CRCC.CAR_ID
HAVING CRCC.CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID
