WITH FISH_AVG AS (
    SELECT FISH_TYPE, SUM(IFNULL(LENGTH, 10)) / COUNT(FISH_TYPE) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT COUNT(FI.ID) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM FISH_INFO FI
INNER JOIN FISH_AVG FA
ON FI.FISH_TYPE = FA.FISH_TYPE
WHERE FA.AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;
