SELECT CAR_ID, MAX(CASE 
    WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
    ELSE '대여 가능'
END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

# 가장 최근 값으로 가져와 확인해야하기 때문에 MAX() 사용
