SELECT PT_NAME, PT_NO, GEND_CD, AGE, IF (TLNO IS NULL, 'NONE', TLNO) AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;

# IFNULL(값1, 값2) : 값이 있으면 값1, 없으면 값2 출력
# SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, "NONE")
# FROM PATIENT
# WHERE AGE <= 12 AND GEND_CD = 'W'
# ORDER BY AGE DESC, PT_NAME ASC;

# CASE WHEN 사용 풀이
# SELECT PT_NAME, PT_NO, GEND_CD, AGE,
#     CASE
#         WHEN TLNO IS NULL THEN 'NONE'
#         ELSE TLNO 
#         END AS TLNO
# FROM PATIENT
# WHERE AGE <= 12 AND GEND_CD = 'W'
# ORDER BY AGE DESC, PT_NAME ASC; 
