SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND MONTH(CRCRH.START_DATE) = 10
ORDER BY CRCC.CAR_ID DESC;

# WITH CRCRH AS (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE MONTH(START_DATE) = 10
# )

# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = '세단' AND
#         CAR_ID in (SELECT CAR_ID
#                   FROM CRCRH)
# ORDER BY CAR_ID DESC;
