WITH CTE AS (
    SELECT FI.ID, FI.FISH_TYPE, FNI.FISH_NAME, FI.LENGTH,
           MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LENGTH

    FROM FISH_INFO FI
             INNER JOIN FISH_NAME_INFO FNI
                        ON FI.FISH_TYPE = FNI.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM CTE
WHERE LENGTH = MAX_LENGTH
ORDER BY ID;

# SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
# FROM FISH_INFO FI
#          INNER JOIN FISH_NAME_INFO FNI
#                     ON FI.FISH_TYPE = FNI.FISH_TYPE
# WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
#     SELECT FISH_TYPE, MAX(LENGTH)
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# )
